name: snakemake
channels:
  - nodefaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aioeasywebdav=2.4.0=py39hf3d152e_1001
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.13=py39h9399b63_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - bcrypt=4.3.0=py39he612d8f_0
  - boto3=1.37.13=pyhd8ed1ab_0
  - botocore=1.37.13=pyge38_1234567_0
  - brotli-python=1.1.0=py39hf88036b_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cachetools=5.5.2=pyhd8ed1ab_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - coin-or-cbc=2.10.12=h00e76a6_2
  - coin-or-cgl=0.60.9=h82e2f02_4
  - coin-or-clp=1.17.10=h8a7a1e7_1
  - coin-or-osi=0.108.11=h96cc833_4
  - coin-or-utils=2.11.12=h3a12e53_2
  - coincbc=2.10.12=2_metapackage
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - configargparse=1.7=pyhd8ed1ab_1
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=44.0.2=py39h7170ec2_0
  - datrie=0.8.2=py39h8cd3c5a_8
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - dpath=2.2.0=pyha770c72_0
  - dropbox=12.0.2=pyhd8ed1ab_1
  - eido=0.2.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - filechunkio=1.8=py_2
  - frozenlist=1.5.0=py39h9399b63_1
  - ftputil=5.1.0=pyhd8ed1ab_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - google-api-core=2.24.2=pyhd8ed1ab_0
  - google-api-python-client=2.164.0=pyhff2d567_0
  - google-auth=2.38.0=pyhd8ed1ab_0
  - google-auth-httplib2=0.2.0=pyhd8ed1ab_1
  - google-cloud-core=2.4.3=pyhd8ed1ab_0
  - google-cloud-storage=3.1.0=pyhd8ed1ab_0
  - google-crc32c=1.1.2=py39h2cad9fb_6
  - google-resumable-media=2.7.2=pyhd8ed1ab_2
  - googleapis-common-protos=1.69.1=pyhd8ed1ab_0
  - grpcio=1.71.0=py39h169e510_0
  - httplib2=0.22.0=pyhd8ed1ab_1
  - humanfriendly=10.0=pyh707e725_8
  - idna=3.10=pyhd8ed1ab_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libabseil=20250127.0=cxx17_hbbce691_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libgrpc=1.71.0=he753a82_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libprotobuf=5.29.3=h501fc15_0
  - libre2-11=2024.07.02=hba17884_3
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.1=hee588c1_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - logmuse=0.2.8=pyhd8ed1ab_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py39h9399b63_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - multidict=6.1.0=py39h9399b63_2
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.0.2=py39h9cb892a_1
  - oauth2client=4.1.3=pyhd8ed1ab_1
  - openssl=3.4.1=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h3b40f6f_2
  - paramiko=3.5.1=pyhd8ed1ab_0
  - pephubclient=0.4.4=pyhd8ed1ab_1
  - peppy=0.40.7=pyhd8ed1ab_2
  - pip=25.0.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - plac=1.4.3=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - pluggy=1.5.0=pyhd8ed1ab_1
  - ply=3.11=pyhd8ed1ab_3
  - prettytable=3.15.1=pyhd8ed1ab_0
  - propcache=0.2.1=py39h9399b63_1
  - proto-plus=1.26.1=pyhd8ed1ab_0
  - protobuf=5.29.3=py39hbeaf701_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - pulp=2.7.0=py39hf3d152e_1
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.1=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.10.6=pyh3cfb1c2_0
  - pydantic-core=2.27.2=py39he612d8f_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pynacl=1.5.0=py39h8cd3c5a_4
  - pyopenssl=25.0.0=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.3.5=pyhd8ed1ab_0
  - python=3.9.21=h9c0c6dc_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-irodsclient=2.1.0=pyhd8ed1ab_0
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.9=5_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.2=py39h9399b63_2
  - re2=2024.07.02=h9925aae_3
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - reretry=0.11.8=pyhd8ed1ab_1
  - rich=13.9.4=pyhd8ed1ab_1
  - rpds-py=0.23.1=py39h3506688_0
  - rsa=4.9=pyhd8ed1ab_1
  - s3transfer=0.11.4=pyhd8ed1ab_0
  - setuptools=75.8.2=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - slacker=0.14.0=pyhd8ed1ab_1
  - smart_open=7.1.0=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snakemake=7.31.0=hdfd78af_2
  - snakemake-minimal=7.31.0=pyhdfd78af_2
  - stone=3.3.2=pyhd8ed1ab_0
  - stopit=1.1.2=pyhd8ed1ab_1
  - tabulate=0.9.0=pyhd8ed1ab_2
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - toposort=1.10=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.15.2=pyhff008b6_0
  - typer-slim=0.15.2=pyh29332c3_0
  - typer-slim-standard=0.15.2=h801b22e_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2025a=h78e105d_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - uritemplate=4.1.1=pyhd8ed1ab_1
  - urllib3=1.26.19=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.2=py39h8cd3c5a_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.18.3=py39h9399b63_1
  - yte=1.7.0=pyha770c72_1
  - zipp=3.21.0=pyhd8ed1ab_1
